### ISSUE TITLE
brazukcoin.ico is added as an extra item on the desktop (along with the shortcut icon) when it is installed. 

### ISSUE THREAD

**Issue by TheNerd** [brazukcoin/brazukcoinwallet#3]
brazukcoin.ico is added as an extra item on the desktop (along with the shortcut icon) when it is installed. If the icon is deleted, the next time the program is launched, it runs the MSI and "fixes" the installation and puts the ico back on the desktop.

**Comment by brazukcoin** [comment]
Please, can you download again, and reinstall?

Then, let me know!

**Comment by TheNerd** [comment]
I don't see the Windows file under releases. All I see is the source code. Am I missing something?

**Comment by brazukcoin** [comment]
Oops! Try again.

**Comment by TheNerd** [comment]
Fixed!

**Comment by brazukcoin** [comment]
Nice! Thanks for the report!
